[package]
name = "dcr"
version = "0.2.3"
edition = "2024"
build = "build.rs"

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
self-replace = "1"
toml = "1.0.3"
