[project]
name = "dcr"
version = "0.1.0"
description = "Утилита для управления проектами для C/C++"
readme = "README.md"
license = "LICENSE"
authors = [
    { name = "Dexoron" },
    { name = "F1F1FISHKA" }
]
requires-python = ">=3.10"